arduino_path = '/dev/ttyACM0'		# different based on computer.
#arduino_path = '/dev/tty.usbmodem1411' # for Nitzan's Mac

# values below copied from arduino (.ino) file. Side note: They were originally
# generated by observing motors at diff PWMs, but also nice numbers to work with
steer_min_pwm = 1100 # Right
steer_max_pwm = 1800 # Left
steer_null_pwm = 1450
throttle_min_pwm = 1000 # Backward
throttle_max_pwm = 2000 # Forward
throttle_null_pwm = 1500
backward_speed_limit = 1400 # For general safety. (arbitrary)
forward_speed_limit = 1600 # For general safety. (arbitrary)

baudrate = 115200 # used in serial connection to arduino
timeout = 5 #used in serial connection to arduino

state_one_pwm = 1908 	# NN control
state_two_pwm = 1720 	# Human annotation
state_three_pwm = 1432	# Human correction
state_four_pwm = 872	# Calibration

state_pwm_epsilon = 50	# Absolute value error (arbitrary) for pwm of a state
calibration_epsilon = 7 ### Not Used. To be deleted. ###
running_avg_len = 10	# Smoothing prevents car from flipping over. Set to 1 for no smoothing.

nn_min_output = 0	# nn outputs 0 for min pwm actions -- throttle: backwards, steering: right
nn_max_output = 99	# nn outputs 99 for max pwm action -- throttle: backwards, steering: left


