arduino_path = '/dev/tty.usbmodem1411' # different based on computer.

# values below copied from arduino (.ino) file. 
# Originally generated by observing motors at diff PWMs, but also nice numbers to work with
throttle_min_pwm = 1000 # Backward
throttle_max_pwm = 2000 # Forward
throttle_null_pwm = 1500
steer_min_pwm = 1100 # Right
steer_max_pwm = 1800 # Left
steer_null_pwm = 1450

baudrate = 115200
timeout = 5

state_one_pwm = 872		# Calibration? Or Human control for now...
state_two_pwm = 1432	# Human correction
state_three_pwm = 1720 	# Human annotation
state_four_pwm = 1908 	# NN control
state_pwm_epsilon = 50	# Absolute value error (arbitrary) for pwm of a state

nn_min_output = 0	# nn outputs 0 for min pwm actions -- throttle: backwards, steering: right
nn_max_output = 99	# nn outputs 99 for max pwm -- throttle: backwards, steering: left

# models
model_info = [
    {
        'name': 'blank',
        'full_path': '/home/mark/bddcar/path/to/model.py',
        'framework': 'pytorch', # or something else like 'tensorflow'
                                # if your framework isn't supported,
                                # then you will have to convert a
                                # numpy matrix to your networks's
                                # desired type
    },
]


